# Generated by Django 4.0.1 on 2022-01-31 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('aleatorio', models.BooleanField(default=False, verbose_name='Aleatorio')),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuestionario', verbose_name='Cuestionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('correcta', models.BooleanField(default=False, verbose_name='Es la correcta')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuestionario_usuario', verbose_name='Cuestionario')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opciones', verbose_name='Opción')),
            ],
        ),
        migrations.AddField(
            model_name='opciones',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preguntas', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='usuarios',
            field=models.ManyToManyField(through='core.Cuestionario_Usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
