# Generated by Django 4.0.1 on 2022-01-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuestionario',
            options={'verbose_name_plural': 'Cuestionarios'},
        ),
        migrations.AlterModelOptions(
            name='cuestionario_usuario',
            options={'verbose_name_plural': 'Cuestionario_Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='opciones',
            options={'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterModelOptions(
            name='preguntas',
            options={'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuestas',
            options={'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AddField(
            model_name='preguntas',
            name='cuestionario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cuestionario', verbose_name='Cuestionario'),
        ),
    ]
