# Generated by Django 4.0.1 on 2022-01-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cuestionario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='cuestionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.cuestionario', verbose_name='Cuestionario'),
        ),
    ]
