# Generated by Django 4.0.1 on 2022-01-31 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_preguntas_cuestionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='cant_preguntas',
            field=models.IntegerField(default=0, verbose_name='Cantidad Preguntas'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='cant_usuarios',
            field=models.IntegerField(default=0, verbose_name='Cantidad Usuarios'),
        ),
        migrations.AddField(
            model_name='cuestionario_usuario',
            name='cant_correcta',
            field=models.IntegerField(default=0, verbose_name='Cantidad Respuestas Correctas'),
        ),
        migrations.AddField(
            model_name='cuestionario_usuario',
            name='cant_respuestas',
            field=models.IntegerField(default=0, verbose_name='Cantidad Respuestas'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='cant_opciones',
            field=models.IntegerField(default=0, verbose_name='Cantidad Opciones'),
        ),
        migrations.AlterField(
            model_name='cuestionario_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
