# Generated by Django 4.0.1 on 2022-02-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cuestionario_cant_preguntas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opciones',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.preguntas', verbose_name='Pregunta'),
        ),
        migrations.DeleteModel(
            name='Respuestas',
        ),
    ]
