# Generated by Django 4.0.1 on 2022-02-02 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_opciones_pregunta_delete_respuestas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuestionario_usuario', verbose_name='Cuestionario')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opciones', verbose_name='Opción')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preguntas', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
