# Generated by Django 4.0.1 on 2022-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tipo_descripcion_alter_tipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opciones',
            name='titulo',
            field=models.CharField(max_length=500, verbose_name='Título'),
        ),
    ]
